### ISSUE TITLE
Add Showing 0 results state

### ISSUE THREAD

**Issue by aevanson** [PublicisSapient/accessible-ecommerce-demo#180]
- [ ] Update the Showing X of X text to indicate that we're showing 0 products (currently broken)
- [ ] In place of product grid, show helpful message (ask Karen for copy)
- [ ] Remove pagination buttons

**Comment by brianelton** [comment]
confirmed on prod
